test_Django_autocomplete/App/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path, include
from  App.views import *


from dal import autocomplete
from django.urls import re_path as url
from .models import  *






#from .views import CountryAutocomplete

urlpatterns = [
    # Uncomment the next line to enable the admin:
    path('', home),
    path('home/', home),
    path('search/', search_address),
    path('list', search),
    path('address/new/', address_form),
    url(r'^address-autocomp/$', AddressAutocomp.as_view(), name='address-autocomp'),
 
    #url(
    #    'test-autocomplete/',
    #    autocomplete.Select2QuerySetView.as_view(model=FakeAddress),
    #    name='select2_fk',
    #),
    #url(
    #    r'^country-autocomplete/$',
    #    CountryAutocomplete.as_view(),
    #    name='country-autocomplete',
    #),
]

#urlpatterns.extend(TestForm.as_urls())

test_Django_autocomplete/select2App/urls.py
# urls.py
from django.urls import  path

from . import views

urlpatterns = [
    path("create/", views.createView, name="create-view")
]

test_Django_autocomplete/test_Django_autocomplete/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from dal import autocomplete
from django.urls import include, path
from django.urls import re_path as url
import App
import select2App
import devApp
from  App.views import *



urlpatterns = [
    # Uncomment the next line to enable the admin:
    path('app/', include('App.urls')),
    path('/', include('App.urls')),
    path('mainApp/', include('mainApp.urls')),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('select2App', include('select2App.urls')),
    path('', include('devApp.urls')),

    #path('home/', home),
    #path('search/', search_address),
    #path('searchf/', search),
    #path('list/', search),

    #path('address/new/', address_form),
]

test_Django_autocomplete/select2App/models.py
# models.py
from django.conf import settings
from django.db import models


class Book(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    co_authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='co_authored_by')





class Code(models.Model):
    code = models.CharField(max_length=20)
    #EnDesc =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #remarks = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #ArDesc =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

test_Django_autocomplete/select2App/forms.py
# forms.py
import pandas as pd
from django import forms
#from django_select2 import forms as s2forms

#from .models import Code

class createForm(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    check = forms.BooleanField(required=False)


#class CodeWidget(s2forms.ModelSelect2Widget):
#    search_fields = [
#        "code__icontains",
#    ]


##class CodeForm(forms.Form):
##    code = forms.CharField(widget=s2forms.Select2Widget)

#class CodeForm(forms.ModelForm):
#    class Meta:
#        model = Code
#        fields = '__all__'
#        #widgets = {
#        #    'code': CodeWidget
#        #    }

#    def __init__(self, *args,**kwargs):
#        super().__init__(*args, **kwargs)
#        self.fields['code'].queryset= Code.objects.none()






#class AuthorWidget(s2forms.ModelSelect2Widget):
#    search_fields = [
#        "username__icontains",
#        "email__icontains",
#    ]


#class CoAuthorsWidget(s2forms.ModelSelect2MultipleWidget):
#    search_fields = [
#        "username__icontains",
#        "email__icontains",
#    ]


#class BookForm(forms.ModelForm):
#    class Meta:
#        model = models.Book
#        fields = "__all__"
#        widgets = {
#            "author": AuthorWidget,
#            "co_authors": CoAuthorsWidget,
#        }

test_Django_autocomplete/select2App/views.py
# views.py
#from django.http import HttpResponse
#from django.views import generic
from django.shortcuts import render
from .forms import createForm
#from .models import  models



def createView(response):
    form = createForm()
    return render(response, "select2App/createPage.html",{'form': form})

test_Django_autocomplete/select2App/templates/select2App/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django Codes</title>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-2">Django Codes</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

test_Django_autocomplete/select2App/templates/select2App/code_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Book</title>
    {{ form.media.css }}
    <style>
        input, select {
            width: 100%
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    
</head>
<body>
    <h1>Create a new Book</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    {{ form.media.js }}
    <script>
        $(document).ready(function () {
            $('#id_code').select2();
        });
    </script>
</body>
</html>

test_Django_autocomplete/select2App/templates/select2App/createPage.html
{% extends 'base.html' %}




{% block content %}
Create Page 2
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock %}

test_Django_autocomplete/select2App/templates/select2App/xxx.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>